#!/usr/bin/env ruby

require_relative '../lib/move.rb'
# Code your CLI Here
board = [" ", " ", " ", " ", " ", " ", " ", " ", " "]
puts "Welcome to Tic Tac Toe!"
puts "Where would you like to go?"
input = gets.strip
index = input_to_index(index)
move(board, 0, " ")
board = ["X", " ", " ", " ", " ", " ", " ", " ", " "]
display_board(board)

#!/usr/bin/env ruby

require_relative '../lib/move.rb'
# Code your CLI Here
board = ["X", " ", " ", " ", " ", " ", " ", " ", " "]
puts "Welcome to Tic Tac Toe!"
puts "Where would you like to go?"
input = gets.strip
index = input_to_index(index)
move(board, 0, " ")
display_board(board)
puts (" X |   |   ")
